Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,10 +20,10 @@ jobs:
         node-version: '18' # Use the Node.js version you need
 
     - name: Install dependencies
-      run: pnpm install
+      run: npm install
 
     - name: Build Next.js project
-      run: pnpm run build
+      run: npm run build
 
     - name: Copy files via SSH
       uses: appleboy/scp-action@v0.1.2
@@ -41,20 +41,20 @@ jobs:
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
-          # Install pnpm if not already installed
-          if ! command -v pnpm &> /dev/null
+          # Install npm if not already installed
+          if ! command -v npm &> /dev/null
           then
-            echo "pnpm could not be found, installing..."
-            curl -fsSL https://get.pnpm.io/install.sh | bash -
-            export PATH=$HOME/.local/share/pnpm/global/5/.pnpm-store/exec/node_modules/.bin:$PATH
+            echo "npm could not be found, installing..."
+            curl -fsSL https://get.npm.io/install.sh | bash -
+            export PATH=$HOME/.local/share/npm/global/5/.npm-store/exec/node_modules/.bin:$PATH
           fi
 
           # Navigate to project directory
           cd ${{ secrets.EC2_PATH }}
           
           # Install project dependencies and build the project
-          pnpm install
-          pnpm run build
+          npm install
+          npm run build
           
           # Start the application with PM2
           pm2 start npm --name "network_frontend" -- start
